//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CES
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchange
    {
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientId { get; set; }
        public int CurrencyId__Sell_ { get; set; }
        public int CurrencyId__Buy_ { get; set; }
        public int EmployeeId { get; set; }
        public string QuantitySold { get; set; }
        public decimal Sold { get; set; }
        public string QuantityBought { get; set; }
        public decimal Bought { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Revenue { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
